#
# General settings.
#

# Log verbosity. 
# One of panic, fatal, error, warn, info, debug, trace, disabled.
LogLevel = "debug"

# HTTP server IP:port to listen on.
Address = ":11111"

# Directory to serve static files from
WebRoot = "./web/build"

# The path prefix to be used for resolving relative URLs.
# e.g. "/", "/foo/", "/foo/bar/", "/foo/bar/baz/"
BaseURL = "/"

# ReadTimeout is the maximum duration for reading the entire request, 
# including the body, in seconds. 
# A zero or negative value means there will be no timeout.
ReadTimeout = 10

# WriteTimeout is the maximum duration before timing out
# writes of the response, in seconds. 
# It is reset whenever a new request's header is read. 
WriteTimeout = 10

#
# Front-end web socket settings
#
[Frontend]

# Read buffer size in bytes. 
# If size is zero, then buffers allocated by the HTTP server are used. 
# The buffer size does not limit the size of the messages that can be read.
ReadBufferSize = 1024

# Write buffer size in bytes. 
# If size is zero, then buffers allocated by the HTTP server are used. 
# The buffer size does not limit the size of the messages that can be written.
WriteBufferSize = 1024

# Maximum message size allowed from client, in bytes.
MaxMessageSize = 512

# Maximum number of outbound messages to queue up before terminating the connection.
MessageQueueSize = 256

# Time allowed to write a message to the client, in seconds.
WriteTimeout = 10

# Send pings to client with this period, in seconds. 
# Must be less than PongTimeout.
PingInterval = 54

# Time allowed to read the next pong message from the client, in seconds. 
# Must be greater than PingInterval
PongTimeout = 60

# Maximum number of inbound messages allowed per second.
# Exceeding this limit will terminate the connection.
RateLimit = 60

# Maximum number of inbound messages to handle in excess of the specified rate.
RateLimitBurst = 10

#
# Back-end web socket settings
#
[Backend]

# Read buffer size in bytes. 
# If size is zero, then buffers allocated by the HTTP server are used. 
# The buffer size does not limit the size of the messages that can be read.
ReadBufferSize = 1024

# Write buffer size in bytes. 
# If size is zero, then buffers allocated by the HTTP server are used. 
# The buffer size does not limit the size of the messages that can be written.
WriteBufferSize = 1024

# Maximum message size allowed from bot, in bytes.
MaxMessageSize = 512

# Maximum number of outbound messages to queue up before terminating the connection.
MessageQueueSize = 256

# Time allowed to write a message to the bot, in seconds.
WriteTimeout = 10

# Send pings to bot with this period, in seconds. 
# Must be less than PongTimeout.
PingInterval = 54

# Time allowed to read the next pong message from the bot, in seconds. 
# Must be greater than PingInterval
PongTimeout = 60

# Maximum number of inbound messages allowed per second.
# Exceeding this limit will terminate the connection.
RateLimit = 600

# Maximum number of inbound messages allowed in excess of the specified rate.
RateLimitBurst = 10
