#
# General settings.
#

# Log verbosity.
# One of panic, fatal, error, warn, info, debug, trace, disabled.
LogLevel = "debug"

#
# Worker settings
#
[[Worker]]

# An identifier for this pool of workers, used during logging.
Name = "bot"

# Command to run
Command = "./venv/bin/python"

# Command line arguments to pass
Args = ["bot.py"]

# Environment variables in the form "KEY=VALUE".
# e.g. Env = ["FOO=42", "BAR=1", "QUX=SKYNET"]
Env = []

# Working diirectory
Dir = "py"

# How many instances to keep alive.
PoolSize = 1
